### ISSUE TITLE
Does not work with Angular 7

### ISSUE THREAD

**Issue by mebibou** [SnakeByteDevelopment/angulartics2#3]
**Note: for support questions, please use one of these channels:** [Chat: Gitter](https://gitter.im/angulartics/ngx-analytics)

* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When serving the app using angular `7.1.2`, those errors appear in the console:
```
ERROR in node_modules/ngx-analytics/angular-router.d.ts(3,10): error TS2305: Module '"[...]/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ngx-analytics/ngx-analytics.d.ts(1,10): error TS2305: Module '"[...]/node_modules/rxjs/ReplaySubject"' has no exported member 'ReplaySubject'.
node_modules/ngx-analytics/routerless.d.ts(1,10): error TS2305: Module '"[...]/node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/ReplaySubject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/ReplaySubject'.
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**
Should work on Angular 7 or provide instructions on how to use with

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 7.1.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by abdatta** [comment]
Install `rxjs-compat` module to solve this issue temporarily. However, the collaborators should update their `rxjs` library to fix this for future.

**Comment by botoxparty** [comment]
+1 this library should be updated for rxjs 6 support

**Comment by DanielCaspers** [comment]
@ Maintainers, if you'd be willing to accept an outsider who would do the PR, I'd be open to give it a shot. However, I'm not sure how backwards compatible you're looking to be and if RxJS 6/7 is going to be an issue if you'd like to support older versions of Angular. 

If not, I'd be happy to help update temporary documentation so devs don't have to dig into the issue tracker to know why it doesn't work on greenfield angular :)

**Comment by switch87** [comment]
Hi guys, you opened the issue on my very old fork that was used when it was Angular 4 (maybe 5 was just released ...) and never updated after. If you like my addition feel free to fork it and rebase to the original but I will not work on it any more :disappointed:

**Comment by DanielCaspers** [comment]
Is there a newer repository we should look to which you maintain? Thanks!

**Comment by switch87** [comment]
@DanielCaspers No, I'm sorry. Currently I don't use Angular any more, so the project is stranded. If someone likes to get it up to date I would be glad to merge the pull requests though.

**Comment by drdreo** [comment]
So how is the relation of this repo to angulartics2? They seem to still maintain it. What was the core difference of yours and theirs?

**Comment by switch87** [comment]
@drdreo It gives a nicer integration of google analytics, the documentation is also updated about it.

For detailed changes see commit history: https://github.com/SnakeByteDevelopment/angulartics2/commits/master

**Comment by paulatay** [comment]
hi, i tried to update to angular 8 and got stuck with a unit test in ui-router, just want to ask if any one can spare some time to review: https://github.com/paulatay/angulartics2/tree/4.7.0-draft

**Comment by DanielCaspers** [comment]
@paulatay, I need to update a repo using this to Angular 8 and I think I'd have an easier time helping you review the PR and getting this merged than migrating to a new analytics provider. 

Please hit me up at dan@caspers.dev and I can try to offer another set of eyes. I'm no ui-router expert, but I'm willing to give it a shot.
